import {
  Activity,
  AlertTriangle,
  BadgeCheck,
  BarChart3,
  Building2,
  CalendarDays,
  CheckCircle2,
  CheckSquare,
  ClipboardList,
  CreditCard,
  Database,
  FileText,
  FlaskConical,
  Home,
  Hourglass,
  LayoutGrid,
  LogOut,
  MessageSquare,
  Package,
  Pill,
  QrCode,
  ScanLine,
  Search,
  Settings,
  Server,
  Shield,
  TestTube2,
  User,
  Wallet,
  ClipboardPenLine,
  Clock3,
  HeartPulse,
  Receipt,
  Users,
} from "lucide-react";

export const ICONS = {
  home: Home,
  user: User,
  calendar: CalendarDays,
  pill: Pill,
  flask: FlaskConical,
  qr: QrCode,
  "credit-card": CreditCard,
  message: MessageSquare,
  clipboard: ClipboardList,
  logout: LogOut,
  users: Users,
  "check-square": CheckSquare,
  "heart-pulse": HeartPulse,
  scan: ScanLine,
  clock: Clock3,
  layout: LayoutGrid,
  "test-tube": TestTube2,
  "clipboard-edit": ClipboardPenLine,
  "check-circle": CheckCircle2,
  hourglass: Hourglass,
  shield: Shield,
  settings: Settings,
  building: Building2,
  "bar-chart": BarChart3,
  database: Database,
  activity: Activity,
  server: Server,
  "alert-triangle": AlertTriangle,
  "file-text": FileText,
  "badge-check": BadgeCheck,
  receipt: Receipt,
  wallet: Wallet,
  package: Package,
  search: Search,
} as const;

export type IconKey = keyof typeof ICONS;

